# PACMAN - Starship Prompt
format = """\
[](#7C3AED)\
$os\
$shell\
$username\
[](bg:#1a1b26 fg:#7C3AED)\
$directory\
$git_branch\
$git_status\
$fill\
$nix_shell\
$nodejs\
$rust\
$python\
$cmd_duration\
$line_break\
$character\
"""

[os]
disabled = false
style = "bg:#7C3AED fg:#ffffff"

[shell]
disabled = false
style = "bg:#7C3AED fg:#ffffff"

[character]
success_symbol = "[▶](bold #7C3AED)"
error_symbol = "[▶](bold #fb4934)"

[directory]
style = "bg:#1a1b26 fg:#ebdbb2"
truncation_length = 3

[git_branch]
style = "bg:#1a1b26 fg:#98971a"
format = "[ $symbol$branch ]($style)"

[git_status]
style = "bg:#1a1b26 fg:#ebdbb2"

[nodejs]
style = "bg:#1a1b26 fg:#83a598"
format = "[ $symbol($version) ]($style)"

[rust]
style = "bg:#1a1b26 fg:#fe8019"
format = "[ $symbol($version) ]($style)"

[python]
style = "bg:#1a1b26 fg:#b8bb26"
format = "[ $symbol($version) ]($style)"

[cmd_duration]
style = "bg:#1a1b26 fg:#928374"
format = "[ ⏱ $duration ]($style)"

[nix_shell]
style = "bg:#1a1b26 fg:#83a598"
format = "[ $symbol$name ]($style)"

[fill]
style = "bg:#1a1b26"
