# PACMAN - Hyprlock Configuration

background {
    monitor =
    path = screenshot
    color = rgba(1a1b26ee)
    blur_passes = 3
    blur_size = 8
}

input-field {
    monitor =
    size = 300, 50
    outline_thickness = 3
    dots_size = 0.2
    dots_spacing = 0.2
    dots_center = true
    outer_color = rgba(7C3AEDee)
    inner_color = rgba(1a1b26ee)
    font_color = rgba(a9b1d6ee)
    fade_on_empty = true
    placeholder_text = <i>Password...</i>
    hide_input = false
    position = 0, -200
    halign = center
    valign = center
}

label {
    monitor =
    text = $TIME
    color = rgba(a9b1d6ee)
    font_size = 60
    font_family = "Hack Nerd Font"
    position = 0, 100
    halign = center
    valign = center
}
